services:
    wsse_server.security.wsse_authenticator:
        class: Ku\Bundle\WsseServerBundle\Security\Authenticator\WsseAuthenticator
        arguments:
            - @doctrine.orm.entity_manager
            - @wsse_server.application_repository

    wsse_server.listener.check_wsse_security_listener:
        class: Ku\Bundle\WsseServerBundle\EventListener\CheckWsseSecurityLisener
        arguments: [@wsse_server.security.wsse_authenticator]
        tags:
            - { name: 'kernel.event_subscriber' }

    # Se decora el annotation class loader de BeSimple
    # con la finalidad de añadir los headers y metodos
    # necesarios para la seguridad wsse
    wsse_server.service_definition.annotation_class_loader:
        class: Ku\Bundle\WsseServerBundle\ServiceDefinition\Loader\AnnotationClassLoader
        decorates: besimple.soap.definition.loader.annot_class
        arguments:
            - @wsse_server.service_definition.annotation_class_loader.inner
            - @annotation_reader

    wsse_server.security.nonce_generator:
        class: Ku\Bundle\WsseServerBundle\Security\NonceGenerator
        arguments: [ @doctrine.orm.entity_manager ]

    wsse_server.application.default_application_repository:
        class: Ku\Bundle\WsseServerBundle\Application\DefaultApplicationRepository
        arguments: ['%wsse_server.applications%']